[TMP] kernelwide: Drop vendor cruft for now
 * Causing build errors, revisit later

 * /home/undead/los/kernel/oneplus/msm8994/kernel/sched/core.c: In function 'cpu_cfs_quota_per_task_read_s64':
/home/undead/los/kernel/oneplus/msm8994/kernel/sched/core.c:10188:2: error: implicit declaration of function 'cgroup_tg' [-Werror=implicit-function-declaration]
  return tg_get_cfs_quota_per_task(cgroup_tg(cgrp));
  ^
/home/undead/los/kernel/oneplus/msm8994/kernel/sched/core.c:10188:35: warning: passing argument 1 of 'tg_get_cfs_quota_per_task' makes pointer from integer without a cast
  return tg_get_cfs_quota_per_task(cgroup_tg(cgrp));
                                   ^
/home/undead/los/kernel/oneplus/msm8994/kernel/sched/core